// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRdONPl4sJ7sCTDgpBv11UsERPL1By_o',
    appId: '1:738403215696:web:f9acb77a213381b3a52455',
    messagingSenderId: '738403215696',
    projectId: 'cpj-consulta-juridica',
    authDomain: 'cpj-consulta-juridica.firebaseapp.com',
    storageBucket: 'cpj-consulta-juridica.appspot.com',
    measurementId: 'G-DJQXZFLBG0',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmRdONPl4sJ7sCTDgpBv11UsERPL1By_o',
    appId: '1:738403215696:web:f9acb77a213381b3a52455',
    messagingSenderId: '738403215696',
    projectId: 'cpj-consulta-juridica',
    authDomain: 'cpj-consulta-juridica.firebaseapp.com',
    storageBucket: 'cpj-consulta-juridica.appspot.com',
    measurementId: 'G-DJQXZFLBG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBclZXLFuDAkrEmFDJdGXS6l6j7c-XyPI0',
    appId: '1:738403215696:android:5b2271767f3801e0a52455',
    messagingSenderId: '738403215696',
    projectId: 'cpj-consulta-juridica',
    storageBucket: 'cpj-consulta-juridica.appspot.com',
  );
}
